### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by IzzySoft** [DmitryTsyvtsyn/AlgoSortingAnimations#2]
First thanks for making your app available here! Did you already choose a license for your project? If not, maybe the [SPDX license list](https://spdx.org/licenses/) can help you pick one? Asking as I though to add your app to the [IzzyOnDroid repo](https://apt.izzysoft.de/fdroid), which would require it to have a F/LOSS license :wink:

Thanks in advance!

**Comment by IzzySoft** [comment]
No choice made yet, @DmitryTsyvtsyn?

**Comment by DmitryTsyvtsyn** [comment]
Sorry, I didn't notice the message, added a MIT license

**Comment by IzzySoft** [comment]
Thanks @DmitryTsyvtsyn! Adding it to the [IzzyOnDroid repo](https://apt.izzysoft.de/fdroid) now. Btw, scanner here reports:

```
SigningBlock blobs:
-------------------
0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

Easily fixed with a little addition to your `build.gradle`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

One more thing:

At IzzyOnDroid we support [Reproducible Builds](https://reproducible-builds.org/) (see: [Reproducible Builds, special client support and more at IzzyOnDroid](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients)). Congrats, your app is reproducible :partying_face: – but only with a minor adjustment :scream: The APK attached to the release was **not** built from the tagged commit, but from the one following it (after updating Android SDK from 33 to 34). For successful RBs, please make sure the APK is always built from a clean tree at the commit the tag points to :wink: Thanks!

Btw: we've prepared some more [hints on reproducible builds](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds) if you want to take a look. What I just described is what we call the "first basic rule" (or the "golden rule").

Once more, thanks a lot! Your app will [become available here](https://apt.izzysoft.de/packages/io.github.dmitrytsyvtsyn.algosortinganimations) with the next sync around 6 pm UTC (i.e. in about 5h from now), and will carry the green shield of successful RB. Be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there e.g. from your Readme :smiley:
